### ISSUE TITLE
Inconsistent on IOS

### ISSUE THREAD

**Issue by robertoleonardo** [Sian-Lee-SA/honeycomb-menu#21]
hi - I've got honeycomb up and running on my PC browser just fine), but on my iphone and ipad -- both from the home assistant app and from a mobile browser -- MOST of the time it doesn't work.  but it's weird, because every so often it DOES work just fine on mobile, but its rare. 

On PC, the honeycomb pops up and all the buttons show and work.  On mobile, when i hold press to bring it up, the screen dims but the honeycomb pop up doesn't appear. it almost seems like it "appears" but only somewhere offscreen.  

here's the relevant card yaml.  (and i only just recently added the "hold_action" and "tap_action" === none to each of the honeycomb buttons. i read in another thread that was worth a shot, but it didn't make a difference. i was having the same issues even before i added those lines.

          - type: custom:button-card
            entity: climate.pure_hot_cool_link
            icon: mdi:fan
            state_color: true
            tap_action:
              action: call-service
              service: fan.toggle
              service_data:
                entity_id: fan.pure_hot_cool_link
            hold_action:
              action: call-service
              service: honeycomb
              service_data:
                buttons:
                  - icon: mdi:information-variant
                    tap_action:
                      action: more-info
                    hold_action: none
                    double_tap_action: none
                  - icon: mdi:fan-speed-1
                    active: '[[[ return entity.attributes.speed == "low" ]]]'
                    tap_action:
                      action: call-service
                      service: fan.set_speed
                      service_data:
                        entity_id: entity
                        speed: low
                    hold_action: none
                    double_tap_action: none
                  - icon: mdi:fan-speed-2
                    active: '[[[ return entity.attributes.speed == "medium" ]]]'
                    tap_action:
                      action: call-service
                      service: fan.set_speed
                      service_data:
                        entity_id: entity
                        speed: medium
                    hold_action: none
                    double_tap_action: none
                  - icon: mdi:fan-speed-3
                    active: '[[[ return entity.attributes.speed == "high" ]]]'
                    tap_action:
                      action: call-service
                      service: fan.set_speed
                      service_data:
                        entity_id: entity
                        speed: high
                    hold_action: none
                    double_tap_action: none
                  - icon: mdi:radiator
                    tap_action:
                      action: call-service
                      service: climate.set_hvac_mode
                      service_data:
                        entity_id: climate.pure_hot_cool_link
                        hvac_mode: heat
                    hold_action: none
                    double_tap_action: none
                  - icon: mdi:snowflake
                    tap_action:
                      action: call-service
                      service: climate.set_hvac_mode
                      service_data:
                        entity_id: climate.pure_hot_cool_link
                        hvac_mode: cool
                    hold_action: none
                    double_tap_action: none
                entity: fan.pure_hot_cool_link
                autoclose: true
                active: true
            double_tap_action:
              action: call-service
              service: script.dyson_timed_off
            color_type: icon
            size: 35px
            show_icon: true
            show_name: false
            styles:
              card:
                - opacity: 1
                - padding: 15px 0px
                - '--mdc-ripple-color': var(--button-card-light-color)
                - '--mdc-ripple-press-opacity': 0.5
              name:
                - opacity: 1
                - padding: 15px 0px
                - '--mdc-ripple-color': var(--button-card-light-color)
                - '--mdc-ripple-press-opacity': 0.5
            state:
              - value: 'off'
                color: rgba(255, 255, 255, .45)
              - value: unavailable
                color: rgba(255, 255, 255, .45)
              - value: heat
                color: rgba(190, 60, 20, 1)
              - value: cool
                color: rgba(10, 80, 160, 1)

**Comment by Sian-Lee-SA** [comment]
As stated in the readme, only chrome is currently supported
