### ISSUE TITLE
Speed of opening

### ISSUE THREAD

**Issue by senpaiSubby** [Sian-Lee-SA/honeycomb-menu#31]
Hi, is there a way to make the honeycomb menu open faster? It seems extremely slow to animate the menu open.

**Comment by senpaiSubby** [comment]
Thats what I'm referring to. I would like the animation to complete in less time than 1.8 seconds. Is this possible?

**Comment by Sian-Lee-SA** [comment]
No

**Comment by Sian-Lee-SA** [comment]
I believe it should be inside the entry file and within the styles
