### ISSUE TITLE
Limit the number of buttons

### ISSUE THREAD

**Issue by bernardovalente** [Sian-Lee-SA/honeycomb-menu#33]
Hi, 
Is it possible to limit of buttons that get displayed? The problem that I'm having is that when not using the 6 buttons, the unused hexagons ares still displayed
![button2](https://user-images.githubusercontent.com/15112071/210070679-54e73552-2e22-4744-b21b-68f173792bb3.jpg)

It would also be great to auto or manual rearrange the position of the buttons depending on the number used
Thank you for your work, this is an awesome tool!

**Comment by Sian-Lee-SA** [comment]
Just add honeycomb-menu-disabled: transparent to your theme yaml and you can manually position a button with the position property

**Comment by bernardovalente** [comment]
That worked, thank you!

Btw there's a typo in the docs, **styes {**:

```
/* Styles selector is used as a placeholder for syntax highlighting */
styes {
    --honeycomb-menu-icon-color: var(--paper-item-icon-color);
    --honeycomb-menu-icon-active-color: var(--paper-item-icon-active-color);
    --honeycomb-menu-background-color: var(--paper-card-background-color);
    --honeycomb-menu-active-background-color: var(--paper-card-active-background-color, var(--paper-card-background-color));
	--honeycomb-menu-disabled: #9a9a9a6e
}
```

**Comment by Sian-Lee-SA** [comment]
I don't see the typo...?
