### ISSUE TITLE
Menu half loading or not loading

### ISSUE THREAD

**Issue by W1ngR1d3r** [Sian-Lee-SA/honeycomb-menu#38]
Thanks for this great work. 
As I love it, I want to implement it in my floorplan.
Unfortunately, I can't make it work. 
Sometimes the menu loads but sometimes it doesn't.
Moreover, in the same floorplan there is a menu that is "half loading", meaning that the central control loads but the buttons don't load.
To give you more info: when I hold the mouse, in a couple of entities with the menu the picture grays out but in another one is not doing even this.
I'm using Chrome.

This is the code of one of the menus:

                  hold_action:
                    action: call-service
                    service: honeycomb
                    service_data:
                      entity: media_player.android_tv_192_168_1_143
                      size: 150
                      xy_pad:
                        'y':
                          invert: true
                          service: script.turn_on
                          service_data:
                            entity_id: >-
                              {{ ( y_percentage > 0 ? "script.tv_volume_up" :
                              "script.tv_volume_down" ) }}
                      styles:
                        icon:
                          - height: 40%
                          - top: '-3px'
                      buttons:
                        - icon: mdi:television
                          tap_action:
                            action: call-service
                            service: script.tv_power
                        - icon: mdi:power
                          tap_action:
                            action: toggle
                        - icon: mdi:netflix
                          tap_action:
                            action: call-service
                            service: media_player.select_source
                            data:
                              source: Netflix
                            target:
                              entity_id: media_player.android_tv_192_168_1_143
                        - icon: mdi:alpha-h-circle
                          tap_action:
                            action: call-service
                            service: media_player.select_source
                            data:
                              source: com.hbo.hbonow
                            target:
                              entity_id: media_player.android_tv_192_168_1_143
                        - icon: mdi:alpha-d-circle
                          tap_action:
                            action: call-service
                            service: media_player.select_source
                            data:
                              source: Disney+
                            target:
                              entity_id: media_player.android_tv_192_168_1_143
                        - icon: mdi:alpha-p-circle
                          tap_action:
                            action: call-service
                            service: media_player.select_source
                            data:
                              source: Prime Video
                            target:
                              entity_id: media_player.android_tv_192_168_1_143

This is an screenshot after holding down on the TV to show the menu:

![image](https://user-images.githubusercontent.com/107564886/217363619-f31660ab-99d6-486e-abf9-3c1195170ea9.png)

**Comment by Sian-Lee-SA** [comment]
data and target needs to be service_data. All the examples shows this

**Comment by W1ngR1d3r** [comment]
In case this helps, I have looked in the inspect window and when I hold the mouse it shows the following error:

Uncaught TypeError: Cannot read properties of undefined (reading 'createCard')
    at c._createLovelaceCard (honeycomb-menu.js?hacstag=259126760010&v=1:135:1035)
    at c.ready (honeycomb-menu.js?hacstag=259126760010&v=1:135:692)
    at c._enableProperties (typography.js:181:1)
    at a.__enableOrFlushClients (typography.js:181:1)
    at a._readyClients (typography.js:181:1)
    at a._flushClients (typography.js:181:1)
    at a._propertiesChanged (typography.js:181:1)
    at a._flushProperties (typography.js:181:1)
    at a.ready (typography.js:181:1)
    at a._enableProperties (typography.js:181:1)
_createLovelaceCard @ honeycomb-menu.js?hacstag=259126760010&v=1:135
ready @ honeycomb-menu.js?hacstag=259126760010&v=1:135
_enableProperties @ typography.js:181
__enableOrFlushClients @ typography.js:181
_readyClients @ typography.js:181
_flushClients @ typography.js:181
_propertiesChanged @ typography.js:181
_flushProperties @ typography.js:181
ready @ typography.js:181
_enableProperties @ typography.js:181
h @ typography.js:181
n @ typography.js:181
a @ typography.js:181
__stampInstance @ typography.js:181
__insertInstance @ typography.js:181
__updateInstances @ typography.js:181
__render @ typography.js:181
(anonymous) @ typography.js:181
(anonymous) @ typography.js:181
setTimeout (async)
(anonymous) @ typography.js:181
characterData (async)
run @ typography.js:181
setConfig @ typography.js:181
debounce @ typography.js:181
__debounceRender @ typography.js:181
__itemsChanged @ typography.js:181
U @ typography.js:181
C @ typography.js:181
_propertiesChanged @ typography.js:181
_flushProperties @ typography.js:181
__enableOrFlushClients @ typography.js:181
_flushClients @ typography.js:181
_propertiesChanged @ typography.js:181
_flushProperties @ typography.js:181
_invalidateProperties @ typography.js:181
Object.defineProperty.set @ typography.js:181
_assignButtons @ honeycomb-menu.js?hacstag=259126760010&v=1:290
ready @ honeycomb-menu.js?hacstag=259126760010&v=1:290
_enableProperties @ typography.js:181
connectedCallback @ typography.js:181
connectedCallback @ typography.js:181
t.connectedCallback @ typography.js:181
display @ honeycomb-menu.js?hacstag=259126760010&v=1:290
s.callService @ honeycomb-menu.js?hacstag=259126760010&v=1:144
p @ ha-state-icon.ts:20
value @ hui-button-card.ts:310
handleEvent @ styles.ts:372
i @ typography.js:181
e.actionHandler.t.disabled.e.actionHandler.end @ ha-state-icon.ts:20

**Comment by Sian-Lee-SA** [comment]
Seems like you need to do a hard refresh and clear cache on your browser

**Comment by Sian-Lee-SA** [comment]
I've also just made a release that checks this so it's more informative to an end user

**Comment by W1ngR1d3r** [comment]
It worked. I cleared the cache and a hard refresh and now the menu is working.
Just to help other people. I'm making changes in the menu and I have to clear the cache almost after every change.
Thanks again!!!

**Comment by Sian-Lee-SA** [comment]
Strange, shouldn't need to for every change (only dashboard refresh)... Unfortunately Home Assistants internal caching doesn't help either

**Comment by W1ngR1d3r** [comment]
To be more precise, it looks like I have to clear the cache not on every change (I have added new buttons and didn't have to clear cache) but when I add a button that generates an error (sometimes this happens :-)

**Comment by Sian-Lee-SA** [comment]
Ahh OK, I'll probably implement more checks in a future release to avoid the errors. Seems the errors will halt the script flow so when you refresh it starts its flow again.

**Comment by martydingo** [comment]
I am aft am seeing cache issues that are only resolved by some combination of hard-refreshes and standard refreshes also, I seem to have significantly reduced this by shifting 

```
  - url: "/hacsfiles/lovelace-card-tools/card-tools.js?hacstag=16140332811"
    type: module
  - url: "/hacsfiles/button-card/button-card.js?hacstag=146194325342"
    type: module
  - url: "/hacsfiles/honeycomb-menu/honeycomb-menu.js?hacstag=2591267600101"
    type: module
```

to the top of the `resources:` array within Home Assistant's lovelace configuration.

**Comment by Sian-Lee-SA** [comment]
Is this happening mostly when there's an invalid yaml structure or error with formatting etc like posted above? is there anything in your logs when the menu doesn't show?

**Comment by martydingo** [comment]
Yes, it can happen mostly during development. 

Mostly it's the XYPad that causes it. Having a non-successful output of the XYPad (e.g. no value returned, javascript errors) take multiple hard refreshes to see. 

You know I don't ever have this problem with any other card mods, so I can only summarise this to the way this handles exceptions.

**Comment by Sian-Lee-SA** [comment]
Could you elaborate on the other card mods you have installed? please note this isn't a custom card. I can also assure you that the ones I use like browser mod and card mod do show errors randomly from time to time and that they also error if the markup is wrong. I think you also missed the alpha state in the readme.
