### ISSUE TITLE
Honeycomb menu not showing

### ISSUE THREAD

**Issue by Sabream** [Sian-Lee-SA/honeycomb-menu#40]
Hello all!

i'm a newbie and i'm struggling to get the Sian-lee honeycomb menu work...
I've installed through HACS everything: https://imgur.com/o1CThP5
Everything is loaded on resources: https://imgur.com/pZPUdGZ

But it seems i don't see any custom card when i create a new dashboard and if i try to create one manually i can't get it working: https://imgur.com/RxghiZh (tap action works, hold action doesn't)

This is the example code i'm using for my test:
https://pastebin.com/grHt8ji8
and this other test
https://pastebin.com/FGsQveLa

whatever i do, honeycomb menu doesn't show...
am i missing something?

**Comment by Sian-Lee-SA** [comment]
You seem to have indentation issues with your yaml mark up... You can add images directly to your comment which is easier for me to view

**Comment by Sabream** [comment]
i'm trying many samples i've found here but still nothing happens:

![sian](https://user-images.githubusercontent.com/13134262/221423522-f37ca7ef-a0f6-43c6-a74a-f4f1232feebd.JPG)

**Comment by Sian-Lee-SA** [comment]
I would first start with something simple to rule out other issues, next check the console logs on your browser

**Comment by Sian-Lee-SA** [comment]
Also always hard refresh your browser

**Comment by Sabream** [comment]
can i do something simpler than this?

![sian2](https://user-images.githubusercontent.com/13134262/221423891-44577659-0cce-44be-8864-19e750d20294.JPG)

i'm trying this on pc with different browsers, tablet and iphone.

this is the error i get on browser console:
https://pastebin.com/G9r0w8TK

**Comment by Sian-Lee-SA** [comment]
Just try one button and you don't need action: none

**Comment by Sian-Lee-SA** [comment]
From my understanding, the menu doesn't work on Apple software, including iOS

**Comment by Sabream** [comment]
It seems it works only on chrome and i was using firefox!
It's really beautifull you did a great job!

**Comment by Sian-Lee-SA** [comment]
Thanks, It's surprising to not work on firefox, pretty sure it worked when I tried a while ago. Will look into it sometime
