### ISSUE TITLE
Buttons not showing when but icons defined

### ISSUE THREAD

**Issue by cgassan** [Sian-Lee-SA/honeycomb-menu#42]
I am trying to use honeycomb module inside a picture-elements.

When I use this code :

![image](https://user-images.githubusercontent.com/125998549/226586938-fb952808-343c-4cfb-941c-f274b5eb508b.png)

The 6 buttons  are showing.

![image](https://user-images.githubusercontent.com/125998549/226584971-5cb8060e-94b1-46fb-ad0e-39824f9fcd26.png)

But when I try to fill the honey buttons using this code :
  
![image](https://user-images.githubusercontent.com/125998549/226587094-17698122-8bca-4a6d-a573-1e7384291e94.png)

The buttons are not showing anymore : 
![image](https://user-images.githubusercontent.com/125998549/226585864-37d3a149-5238-4ae8-b86c-596fb7b7cbad.png)

Any idea what I am doing wrong ?

**Comment by Sian-Lee-SA** [comment]
Is there anything in the logs?

**Comment by cgassan** [comment]
![image](https://user-images.githubusercontent.com/125998549/226619738-65cfed89-0950-4f9d-9b2f-7652afb454a9.png)

**Comment by cgassan** [comment]
Thank you for your quick answer. I am using window and google chrome as browser.

**Comment by Sian-Lee-SA** [comment]
For now, try adding an entity to the buttons as this module is dependent on custom button card. Make sure the button data meets the expectations of that card

**Comment by cgassan** [comment]
When I refresh the page (F5) some error occur on the logs. Maybe that can help for understaying the issue.

![image](https://user-images.githubusercontent.com/125998549/226630584-509a328d-86e5-4dbd-b081-7d8fb33056a7.png)
****

**Comment by Sian-Lee-SA** [comment]
Do you actually have Custom Button Card installed?

**Comment by cgassan** [comment]
I feel really bad... I actually have not installed Custom Button Card. Now everything works fine !
Thank you very for the time you time for me.

**Comment by Sian-Lee-SA** [comment]
All good, glad it's working
