### ISSUE TITLE
Honeycomb menu doesn't work since upgrading to Home Assistant 2023.0.4

### ISSUE THREAD

**Issue by rebmemer** [Sian-Lee-SA/honeycomb-menu#45]
As the title suggests, since upgrading to HA 2023.04 today (released on 04/04/23) - the honeycomb menu no longer works as apparently it relies on polymer, not Lit.  As such, if you try to perform an action to show the menu, you get the below error stating that Polymer support will be "removed in 2023.0.5" but its actually already been removed as shown here;

https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

"In Home Assistant 2023.4, we finally removed the last piece of Polymer from the entry point of Home Assistant, meaning it is not loaded when the app starts, but only when a component needs it."

They claim HA will now load it when needed, but since the update it doesn't work at all so assuming something needs to be done on honeycomb to set polymer up, and also inevitably move to Lit?

![image](https://user-images.githubusercontent.com/13517981/230441303-1dc92d97-63da-46a6-9f60-7e5ec0655b3b.png)

Note: This error did not occur prior to the upgrade, nor did the Polymer prompt.

Thanks

**Comment by Ethanadams642** [comment]
Having the same issue also on 2023.04

**Comment by rebmemer** [comment]
I only downloaded honeycomb yesterday for the first time yesterday, hadn't realised there was a new version releases this morning so I'll give that a try.

**Comment by Sian-Lee-SA** [comment]
Have you done a hard refresh? there is no reference to Polymer anywhere so that warning can't be coming from this module

**Comment by Sian-Lee-SA** [comment]
Also try latest version as Home Assistant has changed their layout structure which card tools can't find the correct element

**Comment by Ethanadams642** [comment]
New HA update and honeycomb update fixed it for me, Thank you.
