### ISSUE TITLE
HA error - Polymer is not defined

### ISSUE THREAD

**Issue by tsigalkos** [Sian-Lee-SA/honeycomb-menu#48]
Hi, since updating to 2023.5.2 I am getting this error. Do you know what is about?

```
Logger: frontend.js.latest.202305033
Source: components/system_log/__init__.py:257
First occurred: 21:05:53 (1 occurrences)
Last logged: 21:05:53

webpack:///./src/honeycomb-menu-item.js?:16:33 Uncaught ReferenceError: Polymer is not defined
```

**Comment by Sian-Lee-SA** [comment]
What version of Honeycomb menu are you using?

**Comment by tsigalkos** [comment]
latest [0.12.2]

**Comment by Sian-Lee-SA** [comment]
> is this relevant?

Not for Honeycomb Menu as this module has been updated to use LitElement and not Polymer... Did you ensure to do a hard refresh (including cache) of your browser?
