### ISSUE TITLE
Feature request: Immediate Action

### ISSUE THREAD

**Issue by k-a-r-g** [Sian-Lee-SA/honeycomb-menu#52]
Hi,

I was quite disappointed when I learned that honeycomb menu is not working on IOS devices, even with the companion app. Anyways, while I still continued to fiddle around with it, honeycomb menu works well and (so far) reliable with the latest update to IOS 16.5.1!

Configuring it for various mobile devices, I noticed a feature that would just well complement the already great menus.
Would it be possible to add the option for an action that is executed while honeycomb menu opens?
For example, like toggling a light when pressing an icon, while also opening the honeycombs for changing light brightness and color. I know there is always a work around with scripts, however, it would just be very elegant to have that as an additional functionality here...

**Comment by Sian-Lee-SA** [comment]
This has been addresssed or talked about in previous threads
