### ISSUE TITLE
Button-card 4.0.0 upgrade breaks honeycomb-menu

### ISSUE THREAD

**Issue by k-a-r-g** [Sian-Lee-SA/honeycomb-menu#54]
button-card 4.0.0 seems to break honeycomb-menu. No buttons are displayed anymore.
Tested with multiple browser, including current Chrome version.

Downgrade to button-card 3.5.0 restores full functionality of honeycomb-menu.

**Comment by Sian-Lee-SA** [comment]
Thanks for raising this, will look into it when I find time. 4.0.0 seems like a big update and breaking changes. Just note that Honeycomb can use other cards for the items if you define it's type

**Comment by SGXander** [comment]
I'm not even using button-card as the caller (using mushroom chips as the caller card) and button-card 4.0.0 and 4.0.1 breaks honeycomb completely for me too. All devices tested (web on phone and panels, android app on phone, web on fridge)

**Comment by Kaibob2** [comment]
Same here. A fix would be nice as almost all entities on my main dashboards picture-elements card rely on the honeycomb menu and are currently unusable :-/

**Comment by Fr3di** [comment]
I would also appreciate a fix for that.
For now I have downgreaded button-card to v3.5.0 which is working fine

**Comment by Sian-Lee-SA** [comment]
Fixed with version (0.13.0)[https://github.com/Sian-Lee-SA/honeycomb-menu/releases/tag/0.13.0]. Personally I'm not a fan of the button card update (although I understand why) but it's also screwed up my icon colors everywhere outside this module. Just extra added chores now.

**Comment by Sian-Lee-SA** [comment]
> I'm not even using button-card as the caller

The icons are based on custom:button-card unless you have specifically changed it in the item config... Doesn't matter what the caller is

**Comment by js-67** [comment]
Update done and it doesn't work

**Comment by Sian-Lee-SA** [comment]
Did you clear cache?

**Comment by js-67** [comment]
yes, Nothing changes

**Comment by Sian-Lee-SA** [comment]
Please provide error log from console

**Comment by js-67** [comment]
The screen becomes dark and the honeycomb does not open. I have to downgrade button card and honeycomb. After for the log I can't find it because I'm starting. sorry

**Comment by js-67** [comment]
0.13.1  Works, thank you very much

**Comment by Kaibob2** [comment]
Same here. Thanks for the fix!
