### ISSUE TITLE
Issue after honeycomb menu upgrade

### ISSUE THREAD

**Issue by leekh406** [Sian-Lee-SA/honeycomb-menu#55]
It got weird after the upgrade, so I looked up the data and came all the way here.
Buton card downgrade to 3.5
It's implemented well on laptops, but it's still weird on mobile.

Let's wait for an improved upgrade version.

**Comment by Sian-Lee-SA** [comment]
You will need to be a bit more detailed on the issue, I can't really go on with "weird" I also don't know if you're referring to the button-card or honeycomb menu... It's possible the mobile is still caching old versions somewhere as they're a bit more involved when it comes to clearing

**Comment by Sian-Lee-SA** [comment]
Could you please provide your yaml. If it works on laptop but not mobile then it seems to be a seperate issue or more directed to Button-Card

**Comment by leekh406** [comment]
> yaml을 제공해 주시겠습니까? 랩톱에서는 작동하지만 모바일에서는 작동하지 않는 경우 별도의 문제이거나 Button-Card에 더 많은 문제가 있는 것 같습니다. 이 글을 쓰면서 모바일에서도 테스트를 하고 있는데 상태가 반영됩니다.

================================================
This is yaml I'm using.

It's still not reflected on mobile.

******************************************

  - type: custom:button-card
    icon: mdi:cctv
    entity: climate.eeokeon
    show_name: false
    styles:
      card:
        - border-radius: 60%
        - width: 25%
    style:
      top: 91.5%
      left: 15%
      opacity: 50%
      size: 0px
      '--paper-item-icon-color': red
    tap_action:
      action: call-service
      service: honeycomb
      service_data:
        entity: switch.tapo_camera_f204_privacy
        buttons:
          - icon: mdi:eye-off-outline
            entity: switch.tapo_camera_f204_privacy
            styles:
              card:
                - background: rgba(153, 255, 153, 0.4)
            active: true
            color_type: card
            style:
              width: 1%
          - icon: mdi:eye-off-outline
            entity: switch.tapo_camera_b334_privacy
            styles:
              card:
                - background: rgba(153, 255, 153, 0.4)
            active: true
            color_type: card
            style:
              width: 1%
          - icon: mdi:cctv
            entity: camera.tapo_camera_f204_hd_stream
            active: true
            color_type: card
            styles:
              card:
                - background: rgba(204, 229, 255, 0.4)
            style:
              width: 1%
          - icon: mdi:cctv
            entity: camera.tapo_camera_b334_hd_stream
            active: true
            color_type: card
            styles:
              card:
                - background: rgba(204, 229, 255, 0.4)
            style:
              width: 1%
          - icon: mdi:cctv
            entity: switch.naebang_kamera_360
            tap_action:
              action: toggle
            active: true
            color_type: card
            styles:
              card:
                - background: rgba(153, 255, 153, 0.4)
            style:
              width: 1%

**Comment by Sian-Lee-SA** [comment]
Please format your code

**Comment by Sian-Lee-SA** [comment]
Also if this is happening with the latest button-card but you reverted the button card to 3.5 but kept honeycomb on latet then this is an issue with custom button card

**Comment by leekh406** [comment]
The honeycomb menu is very pretty..
Every time the HA elements are updated, there is a problem sometimes.
I'm afraid there's been another problem..
First of all, it's working well, but..
1. I asked because the icon status did not change when I turned on the light.
2. It doesn't change when the outlets are turned on and off,

Of course, it works well on the PC and it is not implemented only on the mobile.
Other than this, there is no big problem.

Let's look at the code again.
It happened after the update, so I hope the improved version comes out later.

**Comment by Sian-Lee-SA** [comment]
Ok well, I just tested on both PC and Mobile (Android), I even kept the Honeycomb menu open on the Android device and turned on the light through PC and it reflected immediately on the Mobile device. I'll close for now until I can replicate this issue or another user identifies this problem which could provide more insight. Currently this could simply be a device, user or browser issue on the mobile you're using. The fact it works on PC means the code is running correctly and I can assure that the recent update I made to work with the latest Button Card updated was very minimal and would not affect device or browser compatiblity (you can check the recent commits to ensure this is the case).

**Comment by leekh406** [comment]
honeycomb menu has been restored.
The weird thing is..
The mobile has been restored, but it doesn't work on the PC..

First, I usually use mobile, so the condition is well implemented
Thank God.

They made a pretty menu for me



> 알겠습니다. 방금 PC와 모바일(Android)에서 모두 테스트했습니다. 심지어 Android 기기에서 Honeycomb 메뉴를 열어 놓고 PC를 통해 조명을 켰더니 모바일 기기에 즉시 반영되었습니다. 이 문제를 재현할 수 있거나 다른 사용자가 더 많은 통찰력을 제공할 수 있는 이 문제를 식별할 때까지 지금은 닫겠습니다. 현재 이 문제는 사용 중인 모바일의 장치, 사용자 또는 브라우저 문제일 수 있습니다. PC에서 작동한다는 사실은 코드가 올바르게 실행되고 있음을 의미하며 최신 업데이트된 Button Card와 함께 작동하도록 만든 최근 업데이트는 매우 미미했으며 장치 또는 브라우저 호환성에 영향을 미치지 않을 것이라고 확신할 수 있습니다(최근 커밋을 확인하여 이것이 그 경우 다).


https://github.com/Sian-Lee-SA/honeycomb-menu/assets/128438951/67517070-3a96-4638-8e72-965406080aa6

**Comment by leekh406** [comment]
I deleted the cache for the PC version, and it's working again.

**Comment by Sian-Lee-SA** [comment]
> I deleted the cache for the PC version, and it's working again.

Home Assistant has aggressive caching "issues" along with how browsers handle caching on top... The best way forward when updating frontend cards etc. is appending `?1` to the resource url, then when you update increment the number. This will tell/trick all browsers that the request for the resource is a different file

**Comment by leekh406** [comment]
> > I deleted the cache for the PC version, and it's working again.
> 
> Home Assistant has aggressive caching "issues" along with how browsers handle caching on top... The best way forward when updating frontend cards etc. is appending `?1` to the resource url, then when you update increment the number. This will tell/trick all browsers that the request for the resource is a different file

*********************************************************************************

I got to know honeycomb menu not long after I started home assistant
It's well implemented on PC and mobile.

Thank you for your help~!

**Comment by leekh406** [comment]
It's not an issue, but I have a question.

Implementing xypad among honeycomb menu
Phillips HUE lamp is implemented by referring to the code below.

  xy_pad:
    repeat: 500
    y:
      invert: true
      service: light.turn_on
      service_data:
        entity_id: entity
        brightness_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'

[XYPad Options
 The x and y properties have the same options. If one of the x or y properties are omitted then the pad will only go the direction 
 that's defined.

 The pad can be useful for things like light brightness, color hue rotation, opening and closing shutters or roller doors etc.]

I'm trying to control the speed of "Xiaomi FAN" by referring to the above, but it's not working well.
The code is like this.

  xy_pad:
    y:
      service: fan.turn_on
      service_data:
        entity_id: fan.dmaker_p33_ada1_fan
        fan.speed_step_pct: '[[[ return {{ y_percentage }} / 10; ]]]'

I want to control the speed of Xiaomi FAN on xypad
Looking for advice if it's originally impossible or if the code is wrong.

Thank you..
