### ISSUE TITLE
Buttons not showing up

### ISSUE THREAD

**Issue by medinarj** [Sian-Lee-SA/honeycomb-menu#57]
Hi there,

I have installed your modure with button-card already installed but once I open de menu, the buttons dont show up, just appear as grey.

This is my code:

 - type: custom:button-card
    name: Switch Salon
    icon: mdi:lightbulb
    aspect_ratio: 1/1
    show_name: false
    styles:
      card:
        - border-radius: 50%
        - box-shadow: 0px 0px 2px 0.5px yellow
    style:
      top: 19%
      left: 45%
      width: 3%
    tap_action:
      action: call-service
      service: honeycomb
      service-data:
        buttons:
          - name: Mesilla
            show_name: true
            autoclose: true
            color_type: card
            style:
              width: 1%
            tap_action:
              action: call-service
              service: switch.toggle
              service-data:
                entity: switch.sonoff_1000b01f53

**Comment by medinarj** [comment]
![image](https://github.com/Sian-Lee-SA/honeycomb-menu/assets/72157527/e202ff87-44e5-4cff-b9ae-75499eb73382)

**Comment by BenjaminMaingueneau1** [comment]
same for me...
