### ISSUE TITLE
button in picture-element?

### ISSUE THREAD

**Issue by Eloura74** [Sian-Lee-SA/honeycomb-menu#58]
hello, I'm quite new to the subject but....
I managed to make my floorpla3D
it works, but I spend time creating images, I use the "picture-element", but can I integrate the honeycomb in it, I can't do it

**Comment by Sian-Lee-SA** [comment]
If picture element has an on click action or hold action etc then this menu can be used with it

**Comment by delumerlino** [comment]
> hello, I'm quite new to the subject but.... I managed to make my floorpla3D it works, but I spend time creating images, I use the "picture-element", but can I integrate the honeycomb in it, I can't do it

Did you solved it?
here is my example...
You can copy it, it has variable icons color based on state..

`- type: image
      image: /local/images/myimage.png
      style:
        top: 57%
        left: 5.8%
        width: 11.3%
        opacity: ${(75 - vars[0]) / 100}
      tap_action:
        action: call-service
        service: honeycomb
        service_data:
          buttons:
            - icon: mdi:string-lights
              show_name: true
              show_state: true
              styles:
                icon:
                  - color: |
                      [[[
                        if (states['switch.luce_patio'].state =='on')
                         return 'yellow';
                        return 'LightSteelBlue';
                       ]]]
              tap_action:
                action: toggle
                entity: switch.luce_patio
            - icon: mdi:cctv
              styles:
                icon:
                  - color: |
                      [[[
                        if (states['camera.nord'].state =='unavailable')
                         return 'red';
                        return 'LightSteelBlue';
                       ]]]
              name: CCTV Nord
              tap_action:
                action: more-info
                entity: camera.nord
            - icon: mdi:light-flood-down
              styles:
                icon:
                  - color: |
                      [[[
                        if (states['switch.luce_esterna_nord'].state =='on')
                         return 'yellow';
                        return 'LightSteelBlue';
                       ]]]
              tap_action:
                action: toggle
                entity: switch.luce_esterna_nord
            - icon: mdi:cctv
              styles:
                icon:
                  - color: |
                      [[[
                        if (states['camera.giardino'].state =='unavailable')
                         return 'red';
                        return 'dodgerblue';
                       ]]]
              tap_action:
                action: more-info
                entity: camera.giardino
            - icon: mdi:gate
              color: LightSteelBlue
              tap_action:
                action: toggle
                entity: button.cancelletto_pulse
            - icon: mdi:cancel
              show: false`

**Comment by Eloura74** [comment]
![image](https://github.com/Sian-Lee-SA/honeycomb-menu/assets/95535946/3a07bb43-698e-46ac-9b31-149a204045de)
yes thank you I found it in the meantime, thank you for your answer
