### ISSUE TITLE
HoneyComb Style for button 

### ISSUE THREAD

**Issue by BenjaminMaingueneau1** [Sian-Lee-SA/honeycomb-menu#77]
![image](https://github.com/user-attachments/assets/39bd9212-c07d-40b6-9316-13fd2c3bd89f)

Hi ! how can i get honeyComb button style like this on the picture. Thanks. 

Great job!

**Comment by Sian-Lee-SA** [comment]
closing as those items are not apart of this module, they're not even the same syntax etc.
