### ISSUE TITLE
Honeycomb no longer works with homeassistant beta 2025.1.0b3

### ISSUE THREAD

**Issue by sblogoshs** [Sian-Lee-SA/honeycomb-menu#80]
Hi.
On the Mac with the homeassisatant app and with Safari/Chrome, Honeycomb no longer works with beta 2025.1.0b3, with the app on iPad and iPhone there are no problems. It does not matter whether the old or new version of Honeycomb is used, the entire dashboard is always reduced in size.

**Comment by Sian-Lee-SA** [comment]
As it is beta, you might want to raise this with Home Assistant, something they're doing. Otherwise you can raise this again when HA is in release state.
